USE DB52

DROP TABLE consistsof
DROP TABLE [order]
DROP TABLE payment
DROP TABLE frequent_customer
DROP TABLE customer
DROP TABLE supply
DROP TABLE supplier
DROP TABLE geo_area
DROP TABLE product
DROP TABLE category

CREATE TABLE category(
categorycode INTEGER IDENTITY(1,1) NOT NULL,
[description] TEXT DEFAULT NULL,
CONSTRAINT PK_CATEGORY PRIMARY KEY (categorycode))

CREATE TABLE product(
productcode INTEGER IDENTITY(1,1) NOT NULL,
[name] VARCHAR(20) NOT NULL,
[description] TEXT,
quantity INTEGER,
price MONEY,
categorycode INTEGER NOT NULL,
CONSTRAINT PK_PRODUCT PRIMARY KEY (productcode),
CONSTRAINT FK_PRODUCT FOREIGN KEY (categorycode) REFERENCES category)

CREATE TABLE geo_area(
geocode INTEGER IDENTITY(1,1) NOT NULL,
[name] VARCHAR(20) NOT NULL,
population INTEGER,
CONSTRAINT PK_GEO_AREA PRIMARY KEY (geocode))

CREATE TABLE supplier(
suppliercode INTEGER IDENTITY(1,1) NOT NULL,
ssn VARCHAR(11) NOT NULL UNIQUE,
[name] VARCHAR(20) NOT NULL,
phone VARCHAR(10),
city VARCHAR(20),
street VARCHAR(20),
number INTEGER,
zip INTEGER,
geocode INTEGER NOT NULL,
CONSTRAINT PK_SUPPLIER PRIMARY KEY (suppliercode),
CONSTRAINT FK_SUPPLIER FOREIGN KEY (geocode) REFERENCES geo_area ON UPDATE CASCADE) 

CREATE TABLE supply(
supplycode INTEGER IDENTITY(1,1) NOT NULL,
suppliercode INTEGER NOT NULL,
quantity INTEGER NOT NULL,
[description] TEXT,
shipping_date DATE NOT NULL,
productcode INTEGER NOT NULL,
CONSTRAINT PK_SUPPLY PRIMARY KEY (supplycode),
CONSTRAINT FK_SUPPLYPR FOREIGN KEY (productcode) REFERENCES product ON UPDATE CASCADE,
CONSTRAINT FK_SUPPLYSUP FOREIGN KEY (suppliercode) REFERENCES supplier)

CREATE TABLE customer(
customercode INTEGER IDENTITY(1,1) NOT NULL,
[name] VARCHAR(20) NOT NULL,
ssn VARCHAR(11) UNIQUE NOT NULL,
phone VARCHAR(10),
city VARCHAR(20),
street VARCHAR(20),
number INTEGER,
zip INTEGER,
geocode INTEGER NOT NULL,
CONSTRAINT PK_CUSTOMER PRIMARY KEY (customercode),
CONSTRAINT FK_CUSTOMER FOREIGN KEY (geocode) REFERENCES geo_area ON UPDATE CASCADE)

CREATE TABLE frequent_customer(
customercode INTEGER NOT NULL,
credit_debt MONEY,
credit_limit MONEY NOT NULL,
CONSTRAINT PK_FREQUENT_CUSTOMER PRIMARY KEY (customercode),
CONSTRAINT FK_FREQUENT_CUSTOMER FOREIGN KEY (customercode) REFERENCES customer ON UPDATE CASCADE ON DELETE CASCADE)

CREATE TABLE payment(
customercode INTEGER NOT NULL,
amount MONEY NOT NULL,
payment_date DATE NOT NULL,
CONSTRAINT PK_PAYMENT PRIMARY KEY (customercode, payment_date),
CONSTRAINT FK_PAYMENT FOREIGN KEY (customercode) REFERENCES frequent_customer ON UPDATE CASCADE ON DELETE CASCADE)


CREATE TABLE [order](
ordercode INTEGER IDENTITY(1,1) NOT NULL,
orderdate DATE NOT NULL,
shippingdate DATE NOT NULL,
customercode INTEGER NOT NULL,
CONSTRAINT PK_ORDER PRIMARY KEY (ordercode),
CONSTRAINT FK_ODER FOREIGN KEY (customercode) REFERENCES customer ON UPDATE CASCADE ON DELETE CASCADE)

CREATE TABLE consistsof(
ordercode INTEGER NOT NULL,
productcode INTEGER NOT NULL,
quantity INTEGER NOT NULL,
CONSTRAINT PK_CONSISTSOF PRIMARY KEY(ordercode,productcode),
CONSTRAINT FK_CONSISTSOF_ORD FOREIGN KEY (ordercode) REFERENCES [order] ON DELETE CASCADE,
CONSTRAINT FK_CONSISTSOF_PR FOREIGN KEY (productcode) REFERENCES product ON UPDATE CASCADE ON DELETE CASCADE )